name: CompanyBuilder
favicon: null
layout_spectrum: 0.7436805709730834
typography_spectrum: 0.4507364691235125
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8551476239226758
  lightness: 0.17301756259985268
  saturation: 0.5001013823784888
  rhythmicContrast: 0.6982995814178139
purpose: []
